project:
  type: book

book:
  title: "Aprendizaje Máquina"
  author: "Felipe González"
  chapters:
    - index.qmd
    - 01-introduccion.qmd
    - 02-principios-supervisado.qmd
    - 03-metodos-locales.qmd
    - 04-lineales-ingenieria.qmd
    - 05-regularizacion-1.qmd
    - 06-redes-neuronales-1.qmd
    - 07-intervalos-predictivos.qmd
    - 08-clasificacion-1.qmd
    - 09-clasificacion-2.qmd
    - 10-clasificacion-calibracion.qmd
    - 11-val-cruzada.qmd
    - 12-arboles.qmd
    - 13-arboles-boosting.qmd
  appendices:
    - 81-apendice-descenso.qmd
    - 82-apendice-descenso-estocastico.qmd
    - 99-referencias.qmd

bibliography: referencias/book.bib

format:
  html:
    theme: journal
    lang: es
    font-size: 1.1em
    code-fold: false



